spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: Krithik2020

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
